### ISSUE TITLE
Don't boot

### ISSUE THREAD

**Issue by vinipachecov** [huburtx/Dell-Latitude-3490-hackintosh-Open-Core-0.6.2#3]
Hey mate! Amazing job you did, no Open core did work previously in my Dell latitude 3490, this one almost did it I guess.
Just placed your OC folder into my current Efi folder. 

# Current state
* It does get into the UI to select the OS. 
* It does find all OS installed (can boot my linux installation)
* OC is super fast
* When I select my current Catalina 10.15.17 It gets stuck in the loading screen (with the apple brand icon).

# What I did or didn't do

* I did insert the mac address into the config.plist as requested  README WARNING
* Did not insert the SMBIOS data as I wasn't sure how to do it and what it is.

What could be done to troubleshoot?

**Comment by huburtx** [comment]
You need to add SMBIOS properties in your config.plist (Serial, MLB serial, smUUID).

For this step you can use [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS) or Clover Configurator. 

**Clover Configurator** In SMBIOS section, choose the same MacBookPro model that in the config.plist and copy the values that I mentioned in respective places.

**GenSMBIOS** Follow Dortania guide as indicated below.

For major clarify you can follow the [Dortania guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#platforminfo) for this step.

**Comment by vinipachecov** [comment]
Well, I've generated the SMBIOS with the value in the README MacBookPro15,2 but it kept not working. Is there a way to debug to see which type of error the boot is throwing? 
I've tried to remove the kexts regarding the DW1560. 

Should I try with different values like in the Dortania guide?

**Comment by huburtx** [comment]
Enable verbose mode (add -v boot arg) for to know the error.

Did you have the same bios versio?

Did you set all bios setting as indicated?

Which bootloader release version do you trying? (Catalina or Big Sur)

The model 15,2 is tested and work properly with Dell 3490, however you can try other models (like in Dortania guide), but first thing is enable verbose for debugging.

**Comment by vinipachecov** [comment]
* Using boot 15,2
* Bios version 1.9.4

I'll check the bios options and version asap.

![catalina boot](https://user-images.githubusercontent.com/2838834/103349107-bd759f80-4a7a-11eb-9a5f-fddfcc2ca434.jpeg)

Video with the boot verbose logs:
https://drive.google.com/file/d/1msMxNvD1c032nTWCS86HF_81tmCYY6ml/view?usp=sharing

Currently, I'm getting this error.

**Comment by huburtx** [comment]
For Catalina try this [EFI.zip](https://github.com/huburtx/Dell-Latitude-3490-hackintosh-Open-Core/files/5755469/EFI.zip)

Just copy and paste in your EFI partition and try boot.

**Comment by vinipachecov** [comment]
WOW It worked!!!!
Just booted from the Open Core!! And it worked even the touchpad! 💯 

Thank you SO MUCH!

**Comment by huburtx** [comment]
The EFI that you using is my latest release for Catalina (1.6.3 DELL_Latitude_3490_OC_0.6.3) I think you tried by yourself with Big Sur EFI release (wrong for Catalina). Now you have to fix the combojack for headphones (enable verbstub.kext in config.plist and follow the guide that you can find in [release package](https://github.com/huburtx/Dell-Latitude-3490-hackintosh-Open-Core/releases/tag/1.6.3)
